filter:
    excluded_paths:
        - examples/*
        - resources/*
build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit -c tests/phpunit.xml.dist --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'
